points:
  user:
    userWinEnemyLose: 18
    userWinEnemyWin: 14
    userLoseEnemyWin: -10
    userLoseEnemyLose: -6

  enemy:
    userWinEnemyLose: -14
    userWinEnemyWin: 14
    userLoseEnemyWin: 20
    userLoseEnemyLose: -10
